import { Music, Note, Track } from '../utils/audio-utils';

const heartBeatTrack = new Track([
    Note.new('c', 1, 0.5),
    null,
    Note.new('c', 1, 1),
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    Note.new('c', 1, 0.5),
    Note.new('c', 1, 1),
], "sine", 0.5, 0.5, 35);

const accompaniamentTracks = [
    new Track([
        null,
        null,
        null,
        null,
        null,
        null,
        Note.new('a#', 4, 5),
        null,
        null,
        null,
        Note.new('d#', 4, 5),
        null,
        null,
        null,
        Note.new('g#', 4, 5),
        null,
        null,
        null,
        Note.new('a#', 4, 5),
        null,
        null,
        null,
        Note.new('d#', 4, 5)
    ], "sine", 2, 0.02, 11),
    new Track([
        null,
        null,
        null,
        null,
        null,
        null,
        Note.new('a#', 3, 4),
        Note.new('g#', 3, 4),
        Note.new('d#', 3, 4),
        Note.new('f#', 3, 4),
        Note.new('a#', 3, 4),
        Note.new('g#', 3, 4),
        Note.new('d#', 3, 4),
        Note.new('f#', 3, 4),
        Note.new('c#', 2, 4),
        null,
        Note.new('d#', 2, 4),
        null,
        Note.new('a#', 3, 4),
        null,
        null,
        Note.new('a#', 3, 4),
        Note.new('g#', 3, 4),
        Note.new('a#', 3, 4),
        Note.new('f#', 3, 4),
        Note.new('a#', 3, 4),
        Note.new('g#', 3, 4),
        Note.new('a#', 3, 4),
        Note.new('d#', 3, 4),
        Note.new('a#', 3, 4),
        Note.new('g#', 3, 4),
        Note.new('a#', 3, 4),
        Note.new('f#', 3, 4),
        Note.new('a#', 3, 4),
        Note.new('g#', 3, 4),
        Note.new('a#', 3, 4),
        Note.new('d#', 3, 4),
        null,
        Note.new('f#', 3, 4),
        null,
        Note.new('d#', 3, 4),
        null,
        Note.new('c#', 3, 4),
        null,
        Note.new('d#', 3, 4)
    ], "sine", 2, 0.05, 33),
    new Track([
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        Note.new('d#', 2, 3),
        Note.new('d#', 3, 3),
        Note.new('c#', 2, 3),
        Note.new('c#', 3, 3),
        Note.new('d#', 2, 3),
        Note.new('d#', 3, 3),
        Note.new('c#', 2, 3),
        Note.new('c#', 3, 3),
        Note.new('d#', 2, 3),
        Note.new('d#', 3, 3),
        Note.new('c#', 2, 3),
        Note.new('c#', 3, 3),
        Note.new('d#', 2, 3),
        Note.new('d#', 3, 3),
        Note.new('c#', 2, 3),
        Note.new('c#', 3, 3),
        Note.new('c#', 1, 3),
        Note.new('c#', 2, 3),
        null,
        Note.new('d#', 2, 3),
        Note.new('d#', 3, 3),
        null,
        Note.new('a#', 2, 3),
        Note.new('a#', 3, 3),
        null,
        Note.new('d#', 2, 3),
        Note.new('d#', 3, 3),
        Note.new('c#', 2, 3),
        Note.new('d#', 2, 3),
        Note.new('d#', 3, 3),
        Note.new('c#', 2, 3),
        Note.new('c#', 3, 3),
        Note.new('d#', 2, 3),
        Note.new('d#', 3, 3),
        Note.new('c#', 2, 3),
        Note.new('c#', 3, 3),
        Note.new('d#', 2, 3),
        Note.new('d#', 3, 3),
        Note.new('c#', 2, 3),
        Note.new('c#', 3, 3),
        Note.new('d#', 2, 3),
        Note.new('d#', 3, 3),
        Note.new('c#', 2, 3),
        Note.new('c#', 3, 3),
        Note.new('c#', 1, 3),
        Note.new('c#', 2, 3),
        Note.new('d#', 2, 3),
        Note.new('d#', 3, 3),
        Note.new('c#', 2, 3),
        Note.new('d#', 2, 3),
        Note.new('d#', 3, 3),
        Note.new('c#', 2, 3),
        Note.new('c#', 3, 3),
        Note.new('d#', 2, 3),
        Note.new('d#', 3, 3),
        Note.new('c#', 2, 3),
        Note.new('c#', 3, 3),
        Note.new('d#', 2, 3),
        Note.new('d#', 3, 3),
        Note.new('c#', 2, 3),
        Note.new('c#', 3, 3),
        Note.new('d#', 2, 3),
        Note.new('d#', 3, 3),
        Note.new('c#', 2, 3),
        Note.new('c#', 3, 3),
        Note.new('c#', 1, 3)
    ], "sine", 1, 0.05, 6),
];

const melodyTrack = new Track([
    null,
    null,
    Note.new('c#', 6, 4),
    Note.new('f#', 6, 4),
    Note.new('g#', 6, 4),
    Note.new('d#', 6, 4),
    Note.new('a#', 6, 4),
    Note.new('g#', 6, 4),
    Note.new('d#', 6, 4),
    Note.new('f#', 6, 4),
    Note.new('a#', 6, 4),
    Note.new('g#', 6, 4),
    Note.new('d#', 6, 4),
    Note.new('f#', 6, 4),
    Note.new('c#', 7, 4),
    null,
    Note.new('d#', 7, 4),
    null,
    Note.new('a#', 6, 4),
    null,
    null,
    Note.new('a#', 6, 4),
    Note.new('g#', 6, 4),
    Note.new('a#', 6, 4),
    Note.new('f#', 6, 4),
    Note.new('a#', 6, 4),
    Note.new('g#', 6, 4),
    Note.new('a#', 6, 4),
    Note.new('d#', 6, 4),
    Note.new('a#', 6, 4),
    Note.new('g#', 6, 4),
    Note.new('a#', 6, 4),
    Note.new('f#', 6, 4),
    Note.new('a#', 6, 4),
    Note.new('g#', 6, 4),
    Note.new('a#', 6, 4),
    Note.new('d#', 6, 4),
    null,
    Note.new('f#', 6, 4),
    null,
    Note.new('d#', 6, 4),
    null,
    Note.new('c#', 6, 4),
    null,
    Note.new('d#', 6, 4)
], "sine", 2, 0.01, 33);

export const music = new Music(
    [melodyTrack, heartBeatTrack, ...accompaniamentTracks],
    240
);